name: "🐞 Bug Report"
description: "Report a bug to help improve the project"
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? Steps to reproduce?
  - type: input
    id: expected
    attributes:
      label: Expected behavior
  - type: input
    id: env
    attributes:
      label: Environment (Browser/OS/.NET)
