name: Build & Deploy Blazor Client

on:
  push:
    branches: [ main ]
    paths:
      - 'src/SqlQuestGame.Client/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet publish src/SqlQuestGame.Client -c Release -o dist
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "src/SqlQuestGame.Client"
          output_location: "dist/wwwroot"
